name: barm
on:
  issue_comment:
    types: [created, edited]
jobs:
  barm:
    if: startsWith(github.event.comment.body, '!barm ')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run barm
        uses: ./.github/actions/barm
        with:
          token: ${{ secrets.PAT_FOR_BARM }}

