name: barm
on:
  issue_comment:
    types: [created, edited]
jobs:
  barm:
    if: startsWith(github.event.comment.body, '!barm ')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: barm
        uses: ./.github/actions/barm

